version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: product-adsgroup-search-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product-adsgroup-search_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:6
    container_name: product-adsgroup-search-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
    container_name: product-adsgroup-search-api
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - '3001:3001'
    volumes:
      - uploads_data:/usr/src/app/src/uploads      
    env_file:
      - .env
    command: npm run dev

  worker:
    build:
      context: .
    container_name: product-adsgroup-search-worker
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - uploads_data:/usr/src/app/src/uploads
    env_file:
      - .env
    command: npm run dev:worker

volumes:
  postgres_data:
  redis_data:
  uploads_data:
